version: '3.8'

services:
  mysql_db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: questiongamedb
      MYSQL_USER: user
      MYSQL_PASSWORD: dukebao
    ports:
      - "6000:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
